### ISSUE TITLE
Generate the list of major controls to CCI based on a system

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openstig-api-compliance#1]
For each checklist in the system grouping, get the matching CCI to NIST major control and show a listing of records that are color coded based on status.

Columns (for now)
- Control Category 
- Associated Checklist
- Associated Vulnerability # 
- Description

Colors:
- Red = Open
- Green = Closed (Not a Finding, Not Applicable)
- Blue = Not Reviewed
- Gray = Not Applicable

**Comment by Cingulara** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/46137145/53802320-89c59f00-3f0f-11e9-8c5c-72b73509ef33.png)

**Comment by degthat8412** [comment]
Might want to add a host column for which checklist is for which host

**Comment by Cingulara** [comment]
I have this list generated. Now I need to format it correctly. Right now it performs this:

- read in the U_CCI_List XML file
- put into the NISTControl list of major controls with "compliance records" for each CCI entry in a CKL file
- cycle through each NISTControl record of CCI-with-control-index and lookup all checklists for that CCI
- fill out the "compliance record" for that entry and add to the listing of records per CCI-with-control-index

**Comment by Cingulara** [comment]
We need to show the columns as such:

* Control Number (i.e. AC-9 (3))
* Control Title from https://nvd.nist.gov/800-53/Rev4/impact/low matching the main part of the major control
* Control Description from somewhere???
• Host
* Checklist title hyperlinked to the actual checklist w/ target of _blank
* VulnID
* Status colored

**Comment by Cingulara** [comment]
We need to shorten this...

The compliance has the
* Index / control
* control title (tbd have to read this in)
* 1 or more checklists and are color coded via font on their overall status

Color code status PER INDEX/CONTROL:
* if anything is open, mark it open
* else if anything is not reviewed, mark it not reviewed
* else if the rest are not applicable and not a finding, mark it green (should be a catch-all else)

**Comment by Cingulara** [comment]
need to add in any controls NOT with CCI against the checklist and just leave them empty to show they need to be looked at.

Also need to order these correctly.

**Comment by Cingulara** [comment]
Need to read in the https://nvd.nist.gov/static/feeds/xml/sp80053/rev4/800-53-controls.xml and put into an in-memory database and do lookups on the index for their respective titles.

**Comment by Cingulara** [comment]
done this finally!
